Refactor Jenkinsfile to use bash shebang

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -24,22 +24,22 @@ pipeline {
 
         stage('Build and Test') {
             steps {
-                sh '''
-                    cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
-                    mvn clean package
-                '''
+                sh '''#!/bin/bash
+cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
+mvn clean package
+'''
             }
         }
 
         stage('Static Code Analysis') {
             steps {
                 withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-                    sh '''
-                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
-                        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
-                            -Dsonar.login=$SONAR_AUTH_TOKEN \
-                            -Dsonar.host.url=${SONAR_URL}
-                    '''
+                    sh '''#!/bin/bash
+cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
+mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+  -Dsonar.login=$SONAR_AUTH_TOKEN \
+  -Dsonar.host.url=${SONAR_URL}
+'''
                 }
             }
         }
@@ -50,10 +50,10 @@ pipeline {
             }
             steps {
                 script {
-                    sh '''
-                        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
-                        docker build -t ${DOCKER_IMAGE} .
-                    '''
+                    sh '''#!/bin/bash
+cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
+docker build -t ${DOCKER_IMAGE} .
+'''
                     docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CRED}") {
                         docker.image("${DOCKER_IMAGE}").push()
                     }
@@ -64,9 +64,29 @@ pipeline {
         stage('Update Deployment File') {
             steps {
                 withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                    sh '''
-                        git config user.email "sahu.santosh1989@gmail.com"
-                        git config user.name "${GIT_USER_NAME}"
+                    sh '''#!/bin/bash
+git config user.email "sahu.santosh1989@gmail.com"
+git config user.name "${GIT_USER_NAME}"
 
-                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" \
-                            java-maven-sonar-argocd-helm-k8s/spring-boot-app
+sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" \
+    java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+
+git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+git commit -m "Update deployment image to version ${BUILD_NUMBER}" || echo "No changes to commit"
+git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
+'''
+                }
+            }
+        }
+
+    }
+
+    post {
+        success {
+            echo "Pipeline completed successfully!"
+        }
+        failure {
+            echo "Pipeline failed. Check the console output for errors."
+        }
+    }
+}
